numero1 = float(input("Qual o primeiro numero?"))
numero2 = float(input("Qual o segundo numero?"))

soma = numero1 + numero2
diferença = numero1-numero2
produto = numero1*numero2
divisao = numero1/numero2

print(f"A soma dos dois números é {soma} \n "
      f"A diferença dos dois números é {diferença} \n "
      f"O produto dos dois números é {produto} \n "
      f"A divisão dos dois números é {divisao}")

 ## \n para pular uma linha f antes das " para formatação
## utilização de {} para puxar a variavel
