cidade = input("cidade ? ")
print("sua cidade e",cidade)

nascimento = int(input("nascimento ? "))
print("Sua data de de nascimento e",nascimento)

altura = float(input("altura ? "))
print("Sua altura e",altura)


#cidade = "Biguaçu"
#ano_nascimento = 1998
#altura = 1.79
#gosta_programar = True

#print(f"Adoro a cidade {cidade}, \n"
#      f"Nasci em {ano_nascimento}, \n"
#      f"Tenho {altura} metros, \n"
#      f"Eu {'gosto' if gosta_programar else 'não gosto'} de programar")